# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a742ee3be65c202e865a1d2cccf034e1868a213eabd8ae8f808905194c5a51471d39c8e12148a889e7a13985f9259535dccd7a793aa5b4ef7d19f59758d8128a

test:
  secret_key_base: 8323ee9c4c436eab4b92b4c540beb7d2edd62f9fda7184f38b71c2009d8b523780c9545b685d94c9f016026ea6d3e43dbdb49cf49cedb10fe1861bdff95da8bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
